### ISSUE TITLE
MemoryError in srm.py

### ISSUE THREAD

**Issue by bam54** [cameronphchen/SRM#2] opened 2016-05-05 01:47 UTC
When I run script_example.sh on a dataset consisting of 500x500 matrices of 64 bit floats, a MemoryError is thrown at line 104 of srm.py:

```
bSig_x = bW.dot(bSig_s).dot(bW.T)
```

It seems that bSig_x is a 250000x250000 matrix of 64 bit floats (~465 GB).  Is this some sort of error?  If not, this is a pretty large memory requirement: do you have any suggestions for getting around this error?

**Comment by bam54** [comment] 2016-05-05 17:08
I just realized that this issue is with the Use_SRM project, for which there is a separate forum for issues.  Feel free relocate this issue to that forum.

**Comment by cameronphchen** [comment] 2016-05-05 17:24
we have an optimized version that resolves this issue (with better memory usage), it will be release soon. Will get back to you once it's released. In the meantime, you can consider using non-probabilistic SRM, which has better memory efficiency and is much faster.  (https://github.com/cameronphchen/Use_SRM/blob/public/code/alignment_algo/srm_noneprob.py)

**Comment by cameronphchen** [comment] 2016-07-28 12:44
Hi @bam54,

Thank you so much for reporting the issue! Just want to let you know that the optimized SRM implementation has been released with BrainIAK (Brain Imaging Analysis Kit) https://github.com/IntelPNI/brainiak. It solves a memory limitation of the original implementation and is significantly faster (fitting dozens of subjects with whole brain voxels in less than a minute). Besides, the software also follows scikit-learn API, so should be straightforward to use. Just want to keep you updated if you want to give it a try, and please let me know if you run into any problem. Thanks!

Best,
Cameron

**Comment by cameronphchen** [comment] 2016-07-28 12:59
I'm closing this issue since the problem is solved with the implementation with brainiak.

**Closed as completed by cameronphchen** 2016-07-28 12:59 UTC
